#!/system/bin/sh
# Permission script
# Written by Roman (birgertime)
# www.edtdev.com
echo 'Running perms'

mkdir -p /data/logs
chmod 777 /data/logs

logFile=/data/logs/perms.log
if [ -f "$logFile" ]; then
  rm "$logFile"
fi
touch "$logFile"
chmod 777 "$logFile"

echo "Setting permissions" >> "$logFile"
chmod 0771 /data/app/

# standard permissions
for file in /system/app/* /system/framework/* /data/app/*; do
  echo "  setting permissions (644) for $file" >> "$logFile"
  chmod 0644 "$file"
done

# init.d and /system/xbin
echo "  chmodding init.d and xbin" >> "$logFile"
chmod 0755 /system/etc/init.d
for file in /system/etc/init.d/* /system/xbin/*; do
  chmod 0755 "$file"
done

# su
echo "  chmodding su" >> "$logFile"
chmod 06755 /system/bin/su
chmod 06755 /system/xbin/su

echo "Permissions set" >> "$logFile"

