#!/system/bin/sh
# Output the script name for easier run-parts debugging
echo Now running $0

mount -t debugfs none /sys/kernel/debug
echo NO_GENTLE_FAIR_SLEEPERS > /sys/kernel/debug/sched_features
umount /sys/kernel/debug

echo 1200000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "smartassV2" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
