#!/system/bin/sh
# Permission script
# Written by Roman (birgertime)
# www.edtdev.com

mkdir /data/teamkang
chmod 777 /data/teamkang
mkdir /data/teamkang/logs
chmod 777 /data/teamkang/logs

logFile=/data/teamkang/logs/S30teamkang_perms.log
if [ -f $logFile ]; then
  rm $logFile
fi
touch $logFile
chmod 777 $logFile

sysrw
echo "Setting permissions" >> $logFile
    chmod 0771 /data/app/
    
    # standard permissions
        for file in /system/app/* /system/framework/* /data/app/*; do
                echo "    setting permissions (644) for $file" >> $logFile
                chmod 0644 $file
        done
    
    # su
    chmod 06755 /system/bin/su
    chmod 06755 /system/xbin/su
    
        
        echo "chmodding init.d folder"
        chmod 0777 /system/etc/init.d
        
    chmod 0755 /system/etc/init.d
        for file in /system/etc/init.d/*; do
                echo "    setting permissions (777) for $file" >> $logFile
                chmod 0755 $file
        done
echo "Permissions set" >> $logFile
sysro