#!/system/bin/sh
#
# file: /system/etc/init.d/S98teamkang_tweaks
#
# Created by Team Kang
#


# Misc tweaks for battery life
# echo "2000" > /proc/sys/vm/dirty_writeback_centisecs
# echo "1000" > /proc/sys/vm/dirty_expire_centisecs

# Minfree Handler
# Values in MB = 10, 16, 24, 68, 76, 92
# echo "2560,4096,6144,17408,19456,23552" > /sys/module/lowmemorykiller/parameters/minfree

# SD card Read-ahead set to 2048kb instead of default 128kb
if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
	/system/xbin/echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
fi

busybox mount -o remount,rw -t rootfs /
sh /system/bin/userinit.sh

# End Team Kang Tweaks - For Now