#!/system/bin/sh
# Output the script name for easier run-parts debugging
echo Now running $0

# Remounts
busybox mount -o remount,noatime,nobh,nodiratime,nodelalloc,noauto_da_alloc,barrier=0 /system /system
busybox mount -o remount,noatime,nobh,nodiratime,nodelalloc,noauto_da_alloc,barrier=0 /cache /cache
busybox mount -o remount,noatime,nodiratime,delalloc,noauto_da_alloc,barrier=0 /data /data

# Make /system and / read only
busybox mount -o ro,remount /system
busybox mount -o ro,remount /

sync;
setprop cm.filesystem.ready 1;

